name: Deploy Genchat-app

on:
  push:
    branches:
      - main
      - develop
    paths: 
      - 'backend/cloudflare-worker/**'
  pull_request:
    types:
      - opened
      - closed
    branches:
      - develop
      - feature/**
      - feat/**
    paths:
      - 'backend/cloudflare-worker/**'
  workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Check if 
      - name: Build and Deploy Backend
        id: update_url
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "4"
          workingDirectory: "./backend/cloudflare-worker"
          preCommands: npm list
          command: deploy
